name: Makefile CI

on:
  push:
    branches: [ "main", "workflow-test" ]
  pull_request:
    branches: [ "main" ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
jobs:
  test_python:
    name: Test Python
    runs-on: ubuntu-latest

    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - run: echo "Beginning tests"
      
      - name: Set Up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'

        # put python path into enviroment var:
      - name: Set Python Path
        run: |
          echo "{PYTHONPATH}=${{ github.workspace }}" >> "$GITHUB_ENV"
        
      - name: Install Dependencies
        run: make requirements
      
      - name: Security Checks
        run: make security-test

      - name: Black Code Style Checks
        run: make run-black

      - name: Test Python Files
        run: make unit-test

      - name: Check Test Coverage
        run: make check-coverage
      
  terraform_deploy:
    runs-on: ubuntu-latest
    needs: test_python
    name: Deploy Terraform 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        # with:
        #   ref: workflow-test
      - name: Terraform Layers
        working-directory: terraform
        run: make terraform-layers-requirements
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: ${{ secrets.AWSREGION }}
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Initialise Terraform
        working-directory: terraform
        run: terraform init
      - name: Plan Terraform
        working-directory: terraform
        run: terraform plan
      # - name: Apply Terraform
      #   working-directory: terraform
      #   run: terraform apply -auto-approve