name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test Pyton
    runs-on: ubuntu-latest

    

    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - run: echo "Begining tests"
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'

        # put python path into enviroment var:
      - name: set python path
        run: |
          echo "{PYTHONPATH}=${{ github.workspace }}" >> "$GITHUB_ENV"
        
      - name: install dependencies
        run: make requirements
      
      # commented out until there is some python to test
      # - name: Test python files
      #   run: make unit-test


      - name: Black code style checks
        run: make run-black

      - name: check test coverage
        run: make check-coverage
      
      - name: security checks
        run: make security-test
